-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 20:01:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bank_automat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bank_automat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bank_automat` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `Bank_automat` ;

-- -----------------------------------------------------
-- Table `Bank_automat`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`owner` (
  `idowner` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idowner`),
  UNIQUE INDEX `idowner_UNIQUE` (`idowner` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank_automat`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`currency` (
  `idcurrency` INT NOT NULL,
  `currency_type` VARCHAR(45) NOT NULL,
  `currency_value` VARCHAR(45) NOT NULL,
  `currency_symbol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcurrency`),
  UNIQUE INDEX `idcurrency_UNIQUE` (`idcurrency` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank_automat`.`holder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`holder` (
  `idholder` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `idaccount` INT NOT NULL,
  PRIMARY KEY (`idholder`),
  UNIQUE INDEX `idholder_UNIQUE` (`idholder` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank_automat`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`account` (
  `idaccount` INT NOT NULL,
  `idowner` INT NOT NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `account_type` VARCHAR(45) NOT NULL,
  `balance` VARCHAR(45) NOT NULL,
  `idholder` INT NOT NULL,
  `iban` VARCHAR(30) NOT NULL,
  `credit_limit` DECIMAL NOT NULL DEFAULT '1000',
  `currency_id` INT NOT NULL,
  PRIMARY KEY (`idaccount`),
  INDEX `idowner_idx` (`idowner` ASC) VISIBLE,
  INDEX `id_currency_idx` (`currency_id` ASC) VISIBLE,
  UNIQUE INDEX `idaccount_UNIQUE` (`idaccount` ASC) VISIBLE,
  INDEX `id_holder_idx` (`idholder` ASC) VISIBLE,
  CONSTRAINT `id_owner`
    FOREIGN KEY (`idowner`)
    REFERENCES `Bank_automat`.`owner` (`idowner`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `Bank_automat`.`currency` (`idcurrency`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_holder`
    FOREIGN KEY (`idholder`)
    REFERENCES `Bank_automat`.`holder` (`idholder`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank_automat`.`atm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`atm` (
  `idatm` INT NOT NULL AUTO_INCREMENT,
  `serial_number` VARCHAR(45) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idatm`),
  UNIQUE INDEX `serial_number_UNIQUE` (`serial_number` ASC) VISIBLE,
  UNIQUE INDEX `idatm_UNIQUE` (`idatm` ASC) VISIBLE,
  UNIQUE INDEX `ip_address_UNIQUE` (`ip_address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank_automat`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`transaction` (
  `idtrans` INT NOT NULL,
  `trans_date` TIMESTAMP(6) NOT NULL,
  `trans_type` INT NOT NULL,
  `trans_amount` DECIMAL NOT NULL,
  `targetaccount` VARCHAR(45) NOT NULL,
  `account_id` INT NOT NULL,
  `idatm` INT NOT NULL,
  PRIMARY KEY (`idtrans`),
  UNIQUE INDEX `idtrans_UNIQUE` (`idtrans` ASC) VISIBLE,
  INDEX `id_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `id_atm_idx` (`idatm` ASC) VISIBLE,
  CONSTRAINT `id_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `Bank_automat`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_atm`
    FOREIGN KEY (`idatm`)
    REFERENCES `Bank_automat`.`atm` (`idatm`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `targetacc_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `Bank_automat`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank_automat`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bank_automat`.`card` (
  `idcard` INT NOT NULL,
  `card_type` VARCHAR(20) NOT NULL,
  `idaccount` INT NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `owner_id` INT NOT NULL,
  `pin` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL,
  `issued` DATE NOT NULL,
  `valid` DATE NOT NULL,
  PRIMARY KEY (`idcard`),
  UNIQUE INDEX `idcard_UNIQUE` (`idcard` ASC) VISIBLE,
  INDEX `idaccount_idx` (`idaccount` ASC) VISIBLE,
  CONSTRAINT `idaccount`
    FOREIGN KEY (`idaccount`)
    REFERENCES `Bank_automat`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
