openapi: 3.0.0
info:
  title: OttoHUB Atm API
  version: 1.0.0
  description: API for managing ATM operations
  contact:
    name: Martin Negin, Samu Lyhty, Veikka Koskinen, Topias Perälä
    email: your.email@example.com
servers:
  - url: https://atm.dev.zroot.it
    description: Development server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
paths:
  /atm/{serialNumber}/login:
    post:
      summary: Login to ATM
      description: Login using card number and PIN
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
          description: ATM serial number
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            properties:
              cardNumber:
                type: string
              pin:
                type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  atm:
                    type: object
                    properties:
                      idatm:
                        type: integer
                      serial_number:
                        type: string
                      ip_address:
                        type: string
                      location:
                        type: string
                  card:
                    type: object
                    properties:
                      cardNumber:
                        type: string
                      cardType:
                        type: string
                      attempts:
                        type: integer
                      issued:
                        type: string
                        format: date-time
                      valid:
                        type: string
                        format: date-time
                      status:
                        type: integer
                      account:
                        type: object
                        properties:
                          accountNumber:
                            type: string
                          accountID:
                            type: integer
                          balance:
                            type: string
                          currency:
                            type: integer
                      customer:
                        type: object
                        properties:
                          firstName:
                            type: string
                          lastName:
                            type: string
        '401':
          description: Invalid card number or PIN
        '404':
          description: ATM not found
        '500':
          description: Internal server error
  /atm/{serialNumber}/account:
    get:
      summary: Get account details
      description: Get account details for the logged-in user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
          description: ATM serial number
      responses:
        '200':
          description: Account details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      cardNumber:
                        type: string
        '401':
          description: Unauthorized
        '404':
          description: ATM not found
  /currency:
    get:
      summary: Get a list of currencies
      description: Retrieve a list of all available currencies
      responses:
        '200':
          description: A list of currencies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The currency ID
                    currency_type:
                      type: string
                      description: The type of currency (e.g., USD, EUR)
                    currency_value:
                      type: number
                      description: The value of the currency
                    currency_symbol:
                      type: string
                      description: The symbol of the currency (e.g., $, €)
        '500':
          description: Internal server error
  /currency/now:
    get:
      summary: Update currency rates immediately
      description: Fetch and update the latest currency rates immediately
      responses:
        '200':
          description: Currency rates updated successfully
        '500':
          description: Internal server error
  /transactions/history/{account_id}:
    get:
      summary: Get transaction history for an account
      description: >-
        Retrieve the transaction history for a specific account. Requires a
        valid Bearer token and ATM serial number.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
          description: The ID of the account
        - in: body
          name: serialNumber
          required: true
          schema:
            type: object
            properties:
              serialNumber:
                type: string
          description: The serial number of the ATM
      responses:
        '200':
          description: Transaction history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        idtrans:
                          type: integer
                        account_id:
                          type: integer
                        trans_amount:
                          type: string
                        trans_date:
                          type: string
                          format: date-time
                        trans_method:
                          type: string
        '400':
          description: Missing required parameters (e.g., serialNumber)
        '401':
          description: Unauthorized (invalid or missing token)
        '404':
          description: ATM not found
        '500':
          description: Server error
  /transactions/deposit:
    post:
      summary: Make a deposit
      description: >-
        Deposit money into an account. Requires a valid Bearer token and ATM
        serial number.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: string
                amount:
                  type: number
                idatm:
                  type: string
                idcard:
                  type: string
                serialNumber:
                  type: string
      responses:
        '200':
          description: Deposit successful
        '400':
          description: Missing required parameters (e.g., serialNumber)
        '401':
          description: Unauthorized (invalid or missing token)
        '404':
          description: ATM not found
        '500':
          description: Server error
  /transactions/withdraw:
    post:
      summary: Make a withdrawal
      description: >-
        Withdraw money from an account. Requires a valid Bearer token and ATM
        serial number.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: string
                amount:
                  type: number
                idatm:
                  type: string
                idcard:
                  type: string
                serialNumber:
                  type: string
      responses:
        '200':
          description: Withdrawal successful
        '400':
          description: Missing required parameters (e.g., serialNumber)
        '401':
          description: Unauthorized (invalid or missing token)
        '404':
          description: ATM not found
        '500':
          description: Server error
  /transactions/transfer:
    post:
      summary: Make a transfer
      description: >-
        Transfer money from one account to another. Requires a valid Bearer
        token and ATM serial number.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from_account:
                  type: string
                to_account:
                  type: string
                amount:
                  type: number
                idatm:
                  type: string
                idcard:
                  type: string
                serialNumber:
                  type: string
      responses:
        '200':
          description: Transfer successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
        '400':
          description: Missing required parameters (e.g., serialNumber)
        '401':
          description: Unauthorized (invalid or missing token)
        '404':
          description: ATM not found
        '500':
          description: Server error
  /transactions/{account_id}/display:
    get:
      summary: Display transactions for an account
      description: >-
        Retrieve the last transactions for a specific account. Requires a valid
        Bearer token and ATM serial number.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            type: string
          description: The ID of the account
        - in: body
          name: serialNumber
          required: true
          schema:
            type: object
            properties:
              serialNumber:
                type: string
          description: The serial number of the ATM
      responses:
        '200':
          description: Transactions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        idtrans:
                          type: integer
                        account_id:
                          type: integer
                        trans_amount:
                          type: string
                        trans_date:
                          type: string
                          format: date-time
                        trans_method:
                          type: string
        '400':
          description: Missing required parameters (e.g., serialNumber)
        '401':
          description: Unauthorized (invalid or missing token)
        '404':
          description: ATM not found
        '500':
          description: Server error
tags: []