name: notify

on:
  push:
    branches:
      - backend

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitBrother"
          message: "🎉 Backend branch updated!\n\n**Commit message:** ${{ github.event.head_commit.message }}\n\n**Author:** ${{ github.event.head_commit.author.name }}."
